http_archive(
    name = "build_bazel_rules_apple",
    strip_prefix = "rules_apple-0.7.0",
    urls = ["https://github.com/bazelbuild/rules_apple/archive/0.7.0.tar.gz"], # 2018-08-15
)

load("@build_bazel_rules_apple//apple:repositories.bzl", "apple_rules_dependencies")

apple_rules_dependencies()

http_archive(
    name = "io_bazel_rules_appengine",
    sha256 = "d1fbc9a48332cc00b56d66751b5eb911ac9a88e820af7a2316a9b5ed4ee46d0b",
    strip_prefix = "rules_appengine-0.0.7",
    url = "https://github.com/bazelbuild/rules_appengine/archive/0.0.7.tar.gz",
)

load("@io_bazel_rules_appengine//appengine:appengine.bzl", "appengine_repositories")

appengine_repositories()

android_sdk_repository(
    name = "androidsdk",
    path = "/usr/local/google/home/alexeagle/Android/Sdk",
)
android_ndk_repository(
    name = "androidndk", # Required. Name *must* be "androidndk".
    path = "/usr/local/google/home/alexeagle/Android/Sdk/ndk-bundle", # Optional. Can be omitted if `ANDROID_NDK_HOME` environment variable is set.
)

bind(
    name = "android_sdk_for_testing",
    actual = "@androidsdk//:files",
)

GMAVEN_TAG = "20181010-1" # or the tag from the latest release

http_archive(
    name = "gmaven_rules",
    strip_prefix = "gmaven_rules-%s" % GMAVEN_TAG,
    url = "https://github.com/bazelbuild/gmaven_rules/archive/%s.tar.gz" % GMAVEN_TAG,
)

load("@gmaven_rules//:gmaven.bzl", "gmaven_rules")

gmaven_rules()